name: fclone




on:
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        pip3 install -r ${GITHUB_WORKSPACE}/requirements.txt
        chmod +x ${GITHUB_WORKSPACE}/fclone
        chmod +x ${GITHUB_WORKSPACE}/gclone
        chmod +x ${GITHUB_WORKSPACE}/telegram_gcloner.py
        chmod +x ${GITHUB_WORKSPACE}/restart.py
        sed -i "s/tgtoken/${{ secrets.TGTOKEN }}/g" ${GITHUB_WORKSPACE}/config.ini
        sed -i "s/userid/${{ secrets.USERID }}/g" ${GITHUB_WORKSPACE}/config.ini
        sed -i "s/groupid/${{ secrets.GROUPID }}/g" ${GITHUB_WORKSPACE}/config.ini
        python3 telegram_gcloner.py
