name: pwd




on:
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        pwd
        cd ${GITHUB_WORKSPACE}
        pwd
